### ISSUE TITLE
6.8.3: `PKG-INFO` is missing `License-File` entries

### ISSUE THREAD

**Issue by mtelka** [Python-SIP/sip#5]
The `6.8.3` sdist package at PyPI is missing `License-File` entries in its `PKG-INFO` file.  This is regression from version `6.8.2`.

**Comment by philthompson10** [comment]
I think v6.8.3 was accidentally created with an older version of setuptools. The license files are included in the sdist.

v6.9 will specify a more up to date version of setuptools.
