### ISSUE TITLE
PyQt5-sip 12.16.0 fails to install with Python 3.8

### ISSUE THREAD

**Issue by Gromba** [Python-SIP/sip#56]
I suspect the minimum Python version was not updated to 3.9 on https://pypi.org/project/PyQt5-sip/#history, since it still tries to install version 12.16 on Python 3.8:

`
petbro@box:/tmp/python
> python3 --version
Python 3.8.8
 
petbro@box:/tmp/python
> python3 -m pip install PyQt5-sip
Collecting PyQt5-sip
  Downloading PyQt5_sip-12.16.0.tar.gz (103 kB)
     |████████████████████████████████| 103 kB 8.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: PyQt5-sip
  Building wheel for PyQt5-sip (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: .venv/bin/python3 .venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmprd3uiunm
       cwd: /tmp/pip-install-m5_ryjl5/pyqt5-sip
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'PyQt5.sip' extension
  creating build/temp.linux-x86_64-cpython-38
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall[...] -o build/temp.linux-x86_64-cpython-38/apiversions.o
  In file included from sipint.h:21,
                   from apiversions.c:16:
  sip.h:18:2: error: #error "This version of PyQt5.sip requires Python v3.9 or later"
   **#error "This version of PyQt5.sip requires Python v3.9 or later"**
    ^~~~~
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
`

**Comment by philthompson10** [comment]
Yes, there should be a `requires-python = ">=3.9"` in the `project` section of `pyproject.toml`.

**Comment by woutdenolf** [comment]
Will version `12.16.0` be yanked from pypi? Otherwise we will need to add `PyQt5-sip!=12.16.0` to all our projects that still support python <3.9.

**Comment by philthompson10** [comment]
I will yank it in a day or two after waiting to see if there are any other problems. It's ironic that the 'yank' PEP uses exactly this bug as a justification.

**Comment by ilouzl** [comment]
@philthompson10 
It seems like the same fix has to be applied to PyQT6-sip as well.
Is it also planned to be yanked from pypi?
