### ISSUE TITLE
Parsing error for string annotation on character ':'

### ISSUE THREAD

**Issue by troopa81** [Python-SIP/sip#59]
With the following sip file content

```  
 void printTestDeprecated() /Deprecated="Example: this"/;
```

I get the following error message

```
sip-install: /home/julien/myconf/sip-examples/deprecated/deprecated.sip: line 21: column 31: 'Example' is not a known qualifier
```

There is no other way to escape the ':'

**Comment by philthompson10** [comment]
`:` and `;` can now be escaped with `\`. The documentation has been updated to describe what's going on.

**Comment by troopa81** [comment]
Thanks for fixing
